  
name: Deployer
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to PROD using ssh
      if: contains(github.ref, 'master')
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
         cd repositories/${{ github.event.repository.name }}/
         git checkout master
         git pull origin master
         cp -a * /home/${{ secrets.SSH_USERNAME }}/public_html/parksandrecapi.com
